/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Pocho
 */
public class frmpanelMovies extends javax.swing.JDialog {

    /**
     * Creates new form panelMovies
     */
    public frmpanelMovies(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnPanel1 = new javax.swing.JButton();
        btnPanel2 = new javax.swing.JButton();
        btnPanel3 = new javax.swing.JButton();
        btnPanel4 = new javax.swing.JButton();
        btnPanel5 = new javax.swing.JButton();
        btnPanel6 = new javax.swing.JButton();
        btnPanel7 = new javax.swing.JButton();
        btnPanel8 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btn2ApagarN.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btn2ApagarP.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btn2ApagarH.png"))); // NOI18N
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 359, 64, 64));

        btnPanel1.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel1.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnUsersN.png"))); // NOI18N
        btnPanel1.setText("users");
        btnPanel1.setBorderPainted(false);
        btnPanel1.setContentAreaFilled(false);
        btnPanel1.setFocusPainted(false);
        btnPanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnUsersP.png"))); // NOI18N
        btnPanel1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnUsersH.png"))); // NOI18N
        btnPanel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, 150));

        btnPanel2.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel2.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnConfigN.png"))); // NOI18N
        btnPanel2.setText("config");
        btnPanel2.setBorderPainted(false);
        btnPanel2.setContentAreaFilled(false);
        btnPanel2.setFocusPainted(false);
        btnPanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnConfigP.png"))); // NOI18N
        btnPanel2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnConfigH.png"))); // NOI18N
        btnPanel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 150));

        btnPanel3.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel3.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnMoviesConfN.png"))); // NOI18N
        btnPanel3.setText("MOVI ES");
        btnPanel3.setBorderPainted(false);
        btnPanel3.setContentAreaFilled(false);
        btnPanel3.setFocusPainted(false);
        btnPanel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnMoviesConfP.png"))); // NOI18N
        btnPanel3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnMoviesConfH.png"))); // NOI18N
        btnPanel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 130, 150));

        btnPanel4.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel4.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnBloquearN.png"))); // NOI18N
        btnPanel4.setText("lock");
        btnPanel4.setBorderPainted(false);
        btnPanel4.setContentAreaFilled(false);
        btnPanel4.setFocusPainted(false);
        btnPanel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnBloquearP.png"))); // NOI18N
        btnPanel4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnBloquearH.png"))); // NOI18N
        btnPanel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, 150));

        btnPanel5.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel5.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnMoviesN.png"))); // NOI18N
        btnPanel5.setText("player");
        btnPanel5.setBorderPainted(false);
        btnPanel5.setContentAreaFilled(false);
        btnPanel5.setFocusPainted(false);
        btnPanel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnMoviesP.png"))); // NOI18N
        btnPanel5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnMoviesH.png"))); // NOI18N
        btnPanel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 130, 150));

        btnPanel6.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel6.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnAboutN.png"))); // NOI18N
        btnPanel6.setText("about");
        btnPanel6.setToolTipText("");
        btnPanel6.setBorderPainted(false);
        btnPanel6.setContentAreaFilled(false);
        btnPanel6.setFocusPainted(false);
        btnPanel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnAboutP.png"))); // NOI18N
        btnPanel6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnAboutH.png"))); // NOI18N
        btnPanel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 130, 150));

        btnPanel7.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel7.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnReportsN.png"))); // NOI18N
        btnPanel7.setText("reports");
        btnPanel7.setBorderPainted(false);
        btnPanel7.setContentAreaFilled(false);
        btnPanel7.setFocusPainted(false);
        btnPanel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnReportsP.png"))); // NOI18N
        btnPanel7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnReportsH.png"))); // NOI18N
        btnPanel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 130, 150));

        btnPanel8.setFont(new java.awt.Font("Alien Resurrection", 0, 11)); // NOI18N
        btnPanel8.setForeground(new java.awt.Color(255, 255, 255));
        btnPanel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnInfoN.png"))); // NOI18N
        btnPanel8.setText("SYS I NFO");
        btnPanel8.setBorderPainted(false);
        btnPanel8.setContentAreaFilled(false);
        btnPanel8.setFocusPainted(false);
        btnPanel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanel8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnInfoP.png"))); // NOI18N
        btnPanel8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/btnInfoH.png"))); // NOI18N
        btnPanel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 130, 150));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelMovies/panelMovies.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 804, 435));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpanelMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpanelMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpanelMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpanelMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmpanelMovies dialog = new frmpanelMovies(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanel1;
    private javax.swing.JButton btnPanel2;
    private javax.swing.JButton btnPanel3;
    private javax.swing.JButton btnPanel4;
    private javax.swing.JButton btnPanel5;
    private javax.swing.JButton btnPanel6;
    private javax.swing.JButton btnPanel7;
    private javax.swing.JButton btnPanel8;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
